src/nl/strohalm/cyclos/entities/members/AdminQuery.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

/**
 * Query parameters for administrators
 * @author luis
 */
public class AdminQuery extends ElementQuery {

    private static final long serialVersionUID = 5987596120119119048L;

}

src/nl/strohalm/cyclos/entities/members/Administrator.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

import java.util.Collection;

import nl.strohalm.cyclos.entities.Relationship;
import nl.strohalm.cyclos.entities.access.AdminUser;
import nl.strohalm.cyclos.entities.accounts.AccountOwner;
import nl.strohalm.cyclos.entities.accounts.SystemAccountOwner;
import nl.strohalm.cyclos.entities.customization.fields.AdminCustomField;
import nl.strohalm.cyclos.entities.customization.fields.AdminCustomFieldValue;
import nl.strohalm.cyclos.entities.groups.AdminGroup;
import nl.strohalm.cyclos.utils.CustomFieldsContainer;

/**
 * An administrator is an user with system privilleges
 * @author luis
 */
public class Administrator extends Element implements CustomFieldsContainer<AdminCustomField, AdminCustomFieldValue> {

    public static enum Relationships implements Relationship {
        CUSTOM_VALUES("customValues");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    private static final long                 serialVersionUID = -3378150810991395557L;
    private Collection<AdminCustomFieldValue> customValues;

    @Override
    public AccountOwner getAccountOwner() {
        return SystemAccountOwner.instance();
    }

    public AdminGroup getAdminGroup() {
        return (AdminGroup) super.getGroup();
    }

    public AdminUser getAdminUser() {
        return (AdminUser) super.getUser();
    }

    public Class<AdminCustomField> getCustomFieldClass() {
        return AdminCustomField.class;
    }

    public Class<AdminCustomFieldValue> getCustomFieldValueClass() {
        return AdminCustomFieldValue.class;
    }

    public Collection<AdminCustomFieldValue> getCustomValues() {
        return customValues;
    }

    @Override
    public Element.Nature getNature() {
        return Element.Nature.ADMIN;
    }

    public void setCustomValues(final Collection<AdminCustomFieldValue> customValues) {
        this.customValues = customValues;
    }
}

src/nl/strohalm/cyclos/entities/members/BrokeringQuery.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

import java.util.Calendar;
import java.util.Collection;

import nl.strohalm.cyclos.entities.groups.MemberGroup;
import nl.strohalm.cyclos.utils.query.QueryParameters;

/**
 * Query for brokerings
 * @author luis
 */
public class BrokeringQuery extends QueryParameters {

    public static enum Status {
        ACTIVE, COMMISSION_COMPLETE, PENDING;
    }

    private static final long       serialVersionUID = 1892733819952540734L;
    private Member                  broker;
    private Member                  brokered;
    private String                  username;
    private String                  name;
    private Collection<MemberGroup> groups;
    private Calendar                startExpirationDate;
    private Status                  status;
    private boolean                 returnFinished;

    public Member getBroker() {
        return broker;
    }

    public Member getBrokered() {
        return brokered;
    }

    public Collection<MemberGroup> getGroups() {
        return groups;
    }

    public String getName() {
        return name;
    }

    public Calendar getStartExpirationDate() {
        return startExpirationDate;
    }

    public Status getStatus() {
        return status;
    }

    public String getUsername() {
        return username;
    }

    public boolean isReturnFinished() {
        return returnFinished;
    }

    public void setBroker(final Member broker) {
        this.broker = broker;
    }

    public void setBrokered(final Member brokered) {
        this.brokered = brokered;
    }

    public void setGroups(final Collection<MemberGroup> groups) {
        this.groups = groups;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setReturnFinished(final boolean returnFinished) {
        this.returnFinished = returnFinished;
    }

    public void setStartExpirationDate(final Calendar startExpirationDate) {
        this.startExpirationDate = startExpirationDate;
    }

    public void setStatus(final Status status) {
        this.status = status;
    }

    public void setUsername(final String username) {
        this.username = username;
    }
}

src/nl/strohalm/cyclos/entities/members/Contact.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

import nl.strohalm.cyclos.entities.Entity;
import nl.strohalm.cyclos.entities.Relationship;

/**
 * A member contact
 * @author luis
 */
public class Contact extends Entity {

    public static enum Relationships implements Relationship {
        CONTACT("contact"), OWNER("owner");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }

    private static final long serialVersionUID = 9128456589118721030L;

    private Member            contact;
    private String            notes;
    private Member            owner;

    public Member getContact() {
        return contact;
    }

    public String getNotes() {
        return notes;
    }

    public Member getOwner() {
        return owner;
    }

    public void setContact(final Member contact) {
        this.contact = contact;
    }

    public void setNotes(final String notes) {
        this.notes = notes;
    }

    public void setOwner(final Member owner) {
        this.owner = owner;
    }

    @Override
    public String toString() {
        return getId() + " - " + contact + " contact of " + owner;
    }
}

src/nl/strohalm/cyclos/entities/members/Element.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

import java.util.Calendar;
import java.util.Collection;
import java.util.Map;

import nl.strohalm.cyclos.entities.Entity;
import nl.strohalm.cyclos.entities.Indexable;
import nl.strohalm.cyclos.entities.Relationship;
import nl.strohalm.cyclos.entities.access.User;
import nl.strohalm.cyclos.entities.accounts.AccountOwner;
import nl.strohalm.cyclos.entities.groups.Group;
import nl.strohalm.cyclos.entities.groups.GroupHistoryLog;
import nl.strohalm.cyclos.entities.members.records.MemberRecord;
import nl.strohalm.cyclos.entities.members.remarks.Remark;
import nl.strohalm.cyclos.entities.settings.LocalSettings;
import nl.strohalm.cyclos.utils.ElementVO;
import nl.strohalm.cyclos.utils.StringValuedEnum;

/**
 * A common classes for members and administrators
 * @author luis
 */
public abstract class Element extends Entity implements Indexable {

    public static enum Nature implements StringValuedEnum {
        ADMIN("A"), MEMBER("M"), OPERATOR("O");
        private final String value;

        private Nature(final String value) {
            this.value = value;
        }

        public Class<? extends Element> getElementClass() {
            switch (this) {
                case ADMIN:
                    return Administrator.class;
                case MEMBER:
                    return Member.class;
                case OPERATOR:
                    return Operator.class;
            }
            throw new IllegalStateException("Unknown element nature: " + this);
        }

        public Class<? extends Element> getType() {
            return (this == ADMIN ? Administrator.class : Member.class);
        }

        @Override
        public String getValue() {
            return value;
        }
    }

    public static enum Relationships implements Relationship {
        GROUP("group"), USER("user"), GROUP_HISTORY_LOGS("groupHistoryLogs"), MEMBER_RECORDS("memberRecords"), REMARKS("remarks");
        private final String name;

        private Relationships(final String name) {
            this.name = name;
        }

        @Override
        public String getName() {
            return name;
        }
    }

    private static final long           serialVersionUID = 5024785667579155058L;
    private Calendar                    creationDate;
    private String                      email;
    private Group                       group;
    private String                      name;
    private User                        user;
    private Collection<GroupHistoryLog> groupHistoryLogs;
    private Collection<Remark>          remarks;
    private Collection<MemberRecord>    memberRecords;
    

    /**
     * Returns the account owner that this element represents
     */
    public abstract AccountOwner getAccountOwner();

    public Calendar getCreationDate() {
        return creationDate;
    }

    public String getEmail() {
        return email;
    }

    public Group getGroup() {
        return group;
    }

    public Collection<GroupHistoryLog> getGroupHistoryLogs() {
        return groupHistoryLogs;
    }

    public Collection<MemberRecord> getMemberRecords() {
        return memberRecords;
    }

    @Override
    public String getName() {
        return name;
    }

    public abstract Nature getNature();

    public Collection<Remark> getRemarks() {
        return remarks;
    }

    public User getUser() {
        return user;
    }

    public String getUsername() {
        return user == null ? null : user.getUsername();
    }
  
    /**
     * Determine whether this element is active or not
     */
    public boolean isActive() {
        return group == null ? false : !group.isRemoved();
    }

    @Override
    public final ElementVO readOnlyView() {
        return new ElementVO(getId(), getName(), getUsername(), getGroup().getId(), getNature());
    }

    public void setCreationDate(final Calendar creationDate) {
        this.creationDate = creationDate;
    }

    public void setEmail(final String email) {
        this.email = email;
    }

    public void setGroup(final Group group) {
        this.group = group;
    }

    public void setGroupHistoryLogs(final Collection<GroupHistoryLog> groupHistoryLogs) {
        this.groupHistoryLogs = groupHistoryLogs;
    }

    public void setMemberRecords(final Collection<MemberRecord> memberRecords) {
        this.memberRecords = memberRecords;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setRemarks(final Collection<Remark> remarks) {
        this.remarks = remarks;
    }

    public void setUser(final User user) {
        this.user = user;
        if (user != null) {
            user.setElement(this);
        }
    }

    @Override
    public String toString() {
        return getId() + " - " + getUsername() + " (" + name + ")";
    }

    @Override
    protected void appendVariableValues(final Map<String, Object> variables, final LocalSettings localSettings) {
        variables.put("login", getUsername());
        variables.put("name", name);
        variables.put("email", email);
        variables.put("member", name);
    }
}

src/nl/strohalm/cyclos/entities/members/FullTextAdminQuery.java
/*
    This file is part of Cyclos (www.cyclos.org).
    A project of the Social Trade Organisation (www.socialtrade.org).

    Cyclos is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Cyclos is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Cyclos; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 */
package nl.strohalm.cyclos.entities.members;

import nl.strohalm.cyclos.entities.members.Element.Nature;

/**
 * Query parameters for full-text admin searches
 * @author luis
 */
public class FullTextAdminQuery extends FullTextElementQuery {

    private static final long serialVersionUID = -9146173504271596097L;

    @Override
    public Nature getNature() {
        return Nature.ADMIN;
    }

    @Override
    public Class<? extends ElementQuery> getQueryClass() {
        return AdminQuery.class;
    }
}

WebContent/pages/members/activities/activities.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-bean" prefix="bean" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags/struts-html" prefix="html" %>
<%@ taglib uri="http://sslext.sf.net/tags/sslext" prefix="ssl" %>
<%@ taglib uri="http://devel.cyclos.org/tlibs/cyclos-core" prefix="cyclos" %>

<cyclos:script src="/pages/members/activities/activities.js" />


<table class="defaultTableContent" cellspacing="0" cellpadding="0">
    <tr>
        <td class="tdHeaderTable">
        	<c:choose><c:when test="${myActivities}">
	        	<bean:message key="activities.title.my"/>
	        </c:when><c:otherwise>
		        <bean:message key="activities.title.of" arg0="${member.name}"/>
	        </c:otherwise></c:choose>
        </td>
        <cyclos:help page="reports#member_activities"/>
    </tr>
    <tr>
        <td colspan="2" align="left" class="tdContentTableForms">
            <table class="defaultTable">
            	<tr>
					<td width="30%" class="headerLabel"><bean:message key="activities.sinceActive"/></td>
					<td class="headerField"><cyclos:format date="${activities.sinceActive}"/></td>
	            	<c:if test="${member.group.broker}">
						<td width="30%" class="headerLabel"><bean:message key="activities.brokering.numberMembers"/></td>
						<td class="headerField"><cyclos:format number="${activities.numberBrokeredMembers}" /></td>
					</c:if>
                </tr>
               	
               	<c:if test="${activities.showReferencesInformation}">
	               	<tr>
						<td colspan="4" class="label" style="text-align:left">
							<hr>
							<bean:message key="activities.references"/>
						</td>
					</tr>            	
	               	<tr>
						<td colspan="2" class="headerLabel" width="50%" style="text-align: center"><bean:message key="activities.references.given"/></td>
						<td colspan="2" class="headerLabel" width="50%" style="text-align: center"><bean:message key="activities.references.received"/></td>
					</tr>
					<c:set var="givenReferences" value="${activities.givenReferencesByLevel}"/>
					<c:set var="receivedReferences" value="${activities.receivedReferencesByLevel}"/>
					<c:forEach var="level" items="${referenceLevels}">
		            	<tr>
							<td width="30%" class="headerLabel"><bean:message key="reference.level.${level}"/></td>
							<td width="20%" class="headerField"><cyclos:format number="${givenReferences[level]}" /></td>
							<td width="30%" class="headerLabel"><bean:message key="reference.level.${level}"/></td>
							<td width="20%" class="headerField"><cyclos:format number="${receivedReferences[level]}" /></td>
		                </tr>
					</c:forEach>
				</c:if>
               	
               	<c:if test="${activities.showAdsInformation}">
	               	<tr>
						<td colspan="4" class="label" style="text-align:left">
							<hr>
							<bean:message key="activities.ads"/>
						</td>
					</tr>            	
	            	
	            	<tr>
						<td class="headerLabel"><bean:message key="ad.status.ACTIVE"/></td>
						<td class="headerField"><cyclos:format number="${activities.adsByStatus[adStatus['ACTIVE']]}" /></td>
						<c:if test="${activities.showNonActiveAdsInformation}">
							<td class="headerLabel"><bean:message key="ad.status.EXPIRED"/></td>
							<td class="headerField"><cyclos:format number="${activities.adsByStatus[adStatus['EXPIRED']]}" /></td>
						</c:if>
	                </tr>
					<c:if test="${activities.showNonActiveAdsInformation}">
		            	<tr>
							<td class="headerLabel"><bean:message key="ad.status.PERMANENT"/></td>
							<td class="headerField"><cyclos:format number="${activities.adsByStatus[adStatus['PERMANENT']]}" /></td>
							<td class="headerLabel"><bean:message key="ad.status.SCHEDULED"/></td>
							<td class="headerField"><cyclos:format number="${activities.adsByStatus[adStatus['SCHEDULED']]}" /></td>
		                </tr>
		            </c:if>
	            </c:if>
                
				<c:if test="${activities.showInvoicesInformation}">
	               	<tr>
						<td colspan="4" class="label" style="text-align:left">
							<hr>
							<bean:message key="activities.invoices"/>
						</td>
					</tr>            	
	            	<tr>
						<td width="30%" class="headerLabel"><bean:message key="activities.invoices.outgoing.count"/></td>
						<td class="headerField"><cyclos:format number="${activities.outgoingInvoices.count}" /></td>
						<td width="30%" class="headerLabel"><bean:message key="activities.invoices.outgoing.amount"/></td>
						<td class="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${activities.outgoingInvoices.amount}"/></td>
	                </tr>
	               	<tr>
						<td width="30%" class="headerLabel"><bean:message key="activities.invoices.incoming.count"/></td>
						<td class="headerField"><cyclos:format number="${activities.incomingInvoices.count}" /></td>
						<td width="30%" class="headerLabel"><bean:message key="activities.invoices.incoming.amount"/></td>
						<td class="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${activities.incomingInvoices.amount}"/></td>
	                </tr>
	            </c:if>
			</table>
		</td>
	</tr>
</table>

<c:forEach var="entry" items="${activities.accountActivities}">
	<c:set var="accountName" value="${entry.key}"/>
	<c:set var="accountActivities" value="${entry.value}"/>
	<c:set var="accountStatus" value="${accountActivities.accountStatus}"/>
	<c:set var="unitsPattern" value="${accountStatus.account.type.currency.pattern}"/>
	<c:set var="reservedAmount" value="${cyclos:round(accountStatus.reservedAmount)}"/>
	<c:if test="${activities.showAccountInformation || accountActivities.hasRateInfo}">
		
		<table class="defaultTableContent" cellspacing="0" cellpadding="0">
			<tr>
	   	    	<td class="tdHeaderTable">${accountName}</td>
	        	<td class="tdHelpIcon" height="16">&nbsp;</td>
	    	</tr>
	    	<tr>
	        	<td align="left" class="tdContentTableForms" colspan="2">
	        		<cyclos:layout columns="4" className="defaultTable">
						<c:if test="${activities.showAccountInformation && accountActivities.showAccountInfo}">
            				<cyclos:cell width="30%" className="headerLabel"><bean:message key="account.balance"/></cyclos:cell>
            				<cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountStatus.balance}"/></cyclos:cell>
                   			<cyclos:rowBreak/>
						</c:if>

						<c:if test="${activities.showAccountInformation && accountActivities.showAccountInfo}">
	                       	<c:if test="${accountStatus.creditLimit > 0}">
	                           	<cyclos:cell width="30%" className="headerLabel"><bean:message key="account.creditLimit"/></cyclos:cell>
	                           	<cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${-accountStatus.creditLimit}"/></cyclos:cell>
	                       	</c:if>
	                       	<c:if test="${accountStatus.upperCreditLimit > 0}">
	                           	<cyclos:cell width="30%" className="headerLabel"><bean:message key="account.upperCreditLimit"/></cyclos:cell>
	                           	<cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountStatus.upperCreditLimit}"/></cyclos:cell>
	                       	</c:if>
	                       	<c:if test="${reservedAmount > 0}">
	                           	<cyclos:cell width="30%" className="headerLabel"><bean:message key="account.reservedAmount"/></cyclos:cell>
	                           	<cyclos:cell><cyclos:format unitsPattern="${unitsPattern}" number="${reservedAmount}"/></cyclos:cell>
	                       	</c:if>
	                       	<cyclos:rowBreak/>
	
		            		<cyclos:cell className="headerLabel"><bean:message key="activities.loans.count"/></cyclos:cell>
		            		<cyclos:cell className="headerField"><cyclos:format number="${accountActivities.remainingLoans.count}" /></cyclos:cell>
		            		<cyclos:cell className="headerLabel"><bean:message key="activities.loans.amount"/></cyclos:cell>
		            		<cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.remainingLoans.amount}"/></cyclos:cell>
	
							<cyclos:cell colspan="4" className="label" style="text-align:left">
	                        	<hr>
	                        	<bean:message key="activities.transactions.last30Days"/>
		                    </cyclos:cell>
		                    
		                    <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.numberBuy"/></cyclos:cell>
		                    <cyclos:cell className="headerField"><cyclos:format number="${accountActivities.debitsLast30Days.count}" /></cyclos:cell>
		                    <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.averageBuy"/></cyclos:cell>
	                        <cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.debitsLast30Days.average}"/></cyclos:cell>
	                        
	                        <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.numberSell"/></cyclos:cell>
		                    <cyclos:cell className="headerField"><cyclos:format number="${accountActivities.creditsLast30Days.count}" /></cyclos:cell>
	                        <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.averageSell"/></cyclos:cell>
	                        <cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.creditsLast30Days.average}"/></cyclos:cell>
	                        
							<cyclos:cell colspan="4" className="label" style="text-align:left">
	                         	<hr>
								<bean:message key="activities.transactions.total"/>
		                    </cyclos:cell>
		                    
		                    <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.numberBuy"/></cyclos:cell>
		                    <cyclos:cell className="headerField"><cyclos:format number="${accountActivities.debitsAllTime.count}" /></cyclos:cell>
							<cyclos:cell className="headerLabel"><bean:message key="activities.transactions.averageBuy"/></cyclos:cell>
	                        <cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.debitsAllTime.average}"/></cyclos:cell>
	
		                    <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.numberSell"/></cyclos:cell>
		                    <cyclos:cell className="headerField"><cyclos:format number="${accountActivities.creditsAllTime.count}" /></cyclos:cell>
	                        <cyclos:cell className="headerLabel"><bean:message key="activities.transactions.averageSell"/></cyclos:cell>
	                        <cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.creditsAllTime.average}"/></cyclos:cell>
	                        
		                    <c:if test="${member.group.broker}">
			            		<cyclos:cell colspan="4" className="label" style="text-align:left"><b><bean:message key="activities.brokering"/></b></cyclos:cell>
			            		
				                <cyclos:cell className="headerLabel"><bean:message key="activities.brokering.commission.count"/></cyclos:cell>
			                    <cyclos:cell className="headerField"><cyclos:format number="${accountActivities.brokerCommission.count}" /></cyclos:cell>
		                        <cyclos:cell className="headerLabel"><bean:message key="activities.brokering.commission.amount"/></cyclos:cell>
		                        <cyclos:cell className="headerField"><cyclos:format unitsPattern="${unitsPattern}" number="${accountActivities.brokerCommission.amount}"/></cyclos:cell>
			                </c:if>
		                </c:if>
	    			</cyclos:layout>
	    		</td>
	    	</tr>
	    </table>
	</c:if>
</c:forEach>

<c:if test="${!myActivities}">
	<table class="defaultTableContentHidden"><tr><td>
	<input type="button" id="backButton" class="button" value="<bean:message key="global.back"/>">
	</td></tr></table>
</c:if>